# Generated by Django 3.0.8 on 2020-07-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200730_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joincode',
            name='creater',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to='app.User'),
        ),
        migrations.AlterField(
            model_name='joincode',
            name='joiner',
            field=models.ForeignKey(blank=True, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='joiner', to='app.User'),
        ),
    ]
